### ISSUE TITLE
Too long name in row element

### ISSUE THREAD

**Issue by sailfish009** [prettytable/prettytable#89]
Some elements in the row have a broken column boundary because the name is too long. 

Are there any suitable options for this problem? 

Personally, if the name of the element is too long, 

I would like to have an option to show only part of the name.

**Comment by hugovk** [comment]
Please share some self-contained example code to reproduce the problem.

**Comment by avaish1409** [comment]
I also got the same issue.

Try this:

```python
from prettytable import PrettyTable
x = PrettyTable()

x.field_names = ["City name", "Area", "Population", "Annual Rainfall"]
x.add_row(["Adelaide", 1295, 1158259, 600.5])
x.add_row(["Brisbane", 5905, 1857594, 1146.4])
x.add_row(["abC"*20, 5905, 1857594, 1146.4])

print(x)
```

Output:

![Screenshot from 2021-05-18 12-49-16](https://user-images.githubusercontent.com/47653244/118609217-2797a280-b7d8-11eb-93af-aff229bbe3d6.png)

Here, the display breaks when the window width is lesser than the table width.

Would you consider having a default check for this?

Look forward to contribute a PR!

**Comment by hugovk** [comment]
Thanks for the code example and screenshot.

What sort of change are you thinking of?

How would the API change, and what sort of output would it give with your example?

**Comment by avaish1409** [comment]
Change: if value is long, truncate string (here, something like 'abCabCabC...' should be displayed)

As this issue would arise only while using get_string function, we can check if the output row's width is greater than the current output window size.

This condition check can be added here: https://github.com/jazzband/prettytable/blob/1ab53a5c7cc70fb1bf4f0bfc80120101802359cf/src/prettytable/prettytable.py#L1440

I will look for a better way such that we check for column width rather than entire row's width.

Please guide me if I am mistaken.

**Comment by hugovk** [comment]
I think the default should be off, so that it doesn't alter the current behaviour and break backwards compatibility?

How would you check the window's width? Will this depend on the type of terminal? Or would the user pass a value to limit the table width, like "give me a table with this max width"?

Also if the table width limit is X, there's possibly many columns with long values. How will you decide which of Y columns should be truncated?

**Comment by avaish1409** [comment]
Output window size: os.get_terminal_size()

For multiple columns:

We can calculate a max_col_width for each column based on average length of values in that column and window size. 

So, in general each value will be truncated if it exceeds max_col_width.
